spring.application.name=accounts-user-api

spring.mongodb.uri=${MONGODB_URL}
spring.mongodb.database=${MONGODB_DATABASE}

spring.data.mongodb.auto-index-creation=true

management.endpoints.enabled-by-default=false
management.endpoints.web.base-path=/accounts-user-api/
management.endpoints.web.path-mapping.health= healthcheck
management.endpoint.health.show-details=never
management.endpoint.health.enabled=true
management.endpoint.health.probes.enabled=false

database.limit=${DATABASE_LIMIT:50}

management.opentelemetry.enabled=${OTEL_LOG_ENABLED:false}
management.opentelemetry.logging.export.otlp.endpoint=${OTEL_EXPORTER_OTLP_ENDPOINT}/v1/logs
management.opentelemetry.tracing.export.otlp.endpoint=${OTEL_EXPORTER_OTLP_ENDPOINT}/v1/traces
management.opentelemetry.metrics.export.otlp.endpoint=${OTEL_EXPORTER_OTLP_ENDPOINT}/v1/metrics

